# -*- coding: utf-8 -*-
"""
figs.py — 生成论文 6 张示意图（SVG，纯标准库） / Generates the paper's 6 schematic figures (SVG, stdlib only)
图1 结构–符号样本空间示意；图2 相位模糊对比；图3 三状态反例转移图；
图4 三阶展开几何直观；图5 置换分布直方图（数据）；图6 符号一致性散点图（数据）。
Fig. 1 structure-symbol sample space; Fig. 2 phase ambiguity; Fig. 3 three-state counterexample;
Fig. 4 third-order geometric intuition; Fig. 5 permutation histogram (data); Fig. 6 sign-consistency scatter (data).
本仓库版图内文字为英文（中文论文版由作者原始脚本生成）/ The figure text in this repository
version is English (the Chinese paper version is generated by the author's original scripts).
"""
import json, os
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# 输出目录 / output directory：本仓库版改为脚本所在目录（作者原始脚本指向其本地路径）
# In this repository version the output directory is the script's own directory
# (the author's original script points to his local path).
OUT = os.path.dirname(os.path.abspath(__file__))

def svg_head(w, h):
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">\n<rect width="{w}" height="{h}" fill="white"/>\n'

def svg_tail():
    return "</svg>\n"

def text(x, y, s, size=14, anchor="middle", color="black", weight="normal"):
    return f'<text x="{x}" y="{y}" font-family="Arial, Helvetica, sans-serif" font-size="{size}" text-anchor="{anchor}" fill="{color}" font-weight="{weight}">{s}</text>\n'

def rect(x, y, w, h, fill="#e8f0fe", stroke="#333"):
    return f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" fill="{fill}" stroke="{stroke}" stroke-width="1"/>\n'

def line(x1, y1, x2, y2, color="#333", width=1.5, dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    return f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="{color}" stroke-width="{width}"{d}/>\n'

def arrow(x1, y1, x2, y2, color="#333", width=1.5):
    return line(x1, y1, x2, y2, color, width) + \
        f'<polygon points="{x2:.1f},{y2:.1f} {x2-8:.1f},{y2-4:.1f} {x2-8:.1f},{y2+4:.1f}" fill="{color}"/>\n'

def circle(cx, cy, r, label, fill="#e8f0fe"):
    return f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r}" fill="{fill}" stroke="#333" stroke-width="1.5"/>\n' + text(cx, cy + 5, label, 16)

def fig1():
    s = svg_head(520, 260)
    s += text(260, 24, "Fig. 1  Structure-symbol sample space: the triple (p, tau, P(tau|p))", 15)
    nodes = [("Module", 120, 60), ("FunctionDef", 120, 105), ("Assign", 120, 150), ("Name", 120, 195)]
    for (lab, x, y), (lab2, x2, y2) in zip(nodes[:-1], nodes[1:]):
        s += line(x, y + 12, x2, y2 - 12)
    for lab, x, y in nodes:
        s += rect(x - 60, y - 12, 120, 24)
        s += text(x, y + 4, lab, 13)
    s += text(120, 228, "structure path p (index)", 12)
    s += arrow(180, 195, 340, 150, "#c0392b")
    s += text(240, 165, "P(tau|p)", 14, color="#c0392b")
    s += circle(390, 150, 28, "tau")
    s += text(390, 200, "symbol tau (state)", 12)
    s += rect(40, 32, 440, 195, "none", "#999")
    s += text(260, 40, "atomic events (p, tau); structure is a given index, not an inferred latent variable", 11, color="#666")
    s += text(260, 250, "Caption: p is the ancestor node-type chain; tau is the abstract symbol of the current token", 12, color="#666")
    return s + svg_tail()

def fig2():
    s = svg_head(520, 320)
    s += text(260, 22, "Fig. 2  Phase ambiguity: time indexing vs. structure indexing", 16)
    s += rect(20, 40, 230, 240, "#fdf2f2", "#999")
    s += text(135, 62, "Time indexing: phase unidentifiable", 13, color="#c0392b")
    s += circle(80, 100, 20, "A")
    s += circle(190, 100, 20, "B")
    s += text(135, 135, "P(.|A) = P(.|B)", 12, color="#c0392b")
    for i, ch in enumerate("ababab"):
        s += text(50 + i * 30, 185, ch, 15)
    for i in range(6):
        s += text(50 + i * 30, 215, "?", 15, color="#c0392b")
    s += text(135, 250, "Which position is A? undecidable", 11, color="#c0392b")
    s += rect(270, 40, 230, 240, "#f2f9f2", "#999")
    s += text(385, 62, "Structure indexing: ambiguity resolved", 13, color="#1e8449")
    for i in range(6):
        s += text(300 + i * 30, 100, "ABABAB"[i], 15, color="#1e8449")
    for i, ch in enumerate("ababab"):
        s += text(300 + i * 30, 135, ch, 15)
    s += text(385, 185, "structure is a given index", 12, color="#1e8449")
    s += text(385, 205, "of the sample space,", 12, color="#1e8449")
    s += text(385, 225, "no inference needed", 12, color="#1e8449")
    s += text(385, 250, "(in epsilon-machine language: merged by minimality)", 10, color="#666")
    s += text(260, 312, "Caption: left - phase unidentifiable from symbols alone; right - structure given as index, ambiguity resolved", 12, color="#666")
    return s + svg_tail()

def fig3():
    s = svg_head(620, 320)
    s += text(310, 24, "Fig. 3  Example 1: transition diagram of the three-state counterexample", 15)
    s += circle(150, 70, 26, "A")
    s += circle(450, 70, 26, "B")
    s += circle(300, 240, 26, "C")
    s += arrow(165, 90, 285, 225, "#c0392b")
    s += text(185, 168, "a : 1", 13, color="#c0392b")
    s += arrow(435, 90, 315, 225, "#c0392b")
    s += text(415, 168, "b : 1", 13, color="#c0392b")
    s += arrow(270, 215, 180, 95, "#1e8449")
    s += text(255, 148, "c : 0.5", 13, color="#1e8449")
    s += arrow(330, 215, 420, 95, "#1e8449")
    s += text(345, 148, "d : 0.5", 13, color="#1e8449")
    s += text(310, 283, "Caption: red - edges into C (a:1, b:1); green - edges out of C (c:0.5, d:0.5)", 12, color="#666")
    s += text(310, 306, "S+ ~ S- , yet dS_{A->C} = dS_{B->C} = log 2 > 0", 13, color="#c0392b")
    return s + svg_tail()

def fig4():
    s = svg_head(520, 260)
    s += text(260, 24, "Fig. 4  Geometric intuition for the third-order expansion", 16)
    s += circle(140, 130, 14, "Pf")
    s += circle(380, 130, 14, "Pb")
    s += arrow(150, 95, 370, 95, "#1e8449", 2)
    s += arrow(370, 80, 150, 80, "#1e8449", 2)
    s += text(260, 65, "2nd order: same round-trip distance (Fisher metric); cancels on subtraction", 12, color="#1e8449")
    s += arrow(150, 165, 370, 165, "#c0392b", 2)
    s += arrow(370, 180, 180, 180, "#c0392b", 1.2)
    s += text(260, 215, "3rd order: different round trips (Amari-Chentsov tensor); directionality lives here", 12, color="#c0392b")
    s += text(260, 250, "Caption: top - second-order term round-trip symmetric, cancels; bottom - third-order term asymmetric, source of directionality", 12, color="#666")
    return s + svg_tail()

def fig5():
    d = json.load(open(os.path.join(OUT, "perm_depth5.json"), encoding="utf-8"))
    dist = d["null_a_dist"]
    lo, hi = -0.0105, 0.0105
    nbins = 21
    bw = (hi - lo) / nbins
    counts = [0] * nbins
    for x in dist:
        i = int((x - lo) / bw)
        if 0 <= i < nbins:
            counts[i] += 1
    real = d["real_mean"]
    W, H = 640, 300
    x0, x1 = -0.012, 0.145
    ymax = max(counts) * 1.1
    def X(x): return 50 + (x - x0) / (x1 - x0) * (W - 90)
    def Y(c): return 260 - c / ymax * 200
    s = svg_head(W, H)
    s += text(W/2, 24, "Fig. 5  Permutation-test null distribution (shuffled symbols, author dataset, depth 5, 1000 permutations)", 14)
    s += line(X(x0), Y(0), X(x1), Y(0), "#333", 1)
    for i in range(nbins):
        xc = lo + (i + 0.5) * bw
        s += rect(X(xc - bw/2), Y(counts[i]), X(xc + bw/2) - X(xc - bw/2), Y(0) - Y(counts[i]), "#bcd3f2", "none")
    s += text(X(0), 282, "0", 12)
    s += text(X(0.01), 282, "0.01", 12)
    s += text(X(-0.01), 282, "-0.01", 12)
    s += text(50, 285, "null range [-0.008, +0.009], mean ~ 0", 11, color="#666")
    s += line(X(real), Y(0), X(real), 60, "#c0392b", 2, "6 4")
    s += text(X(real) - 8, 48, f"true <D_asym> = {real:.3f}".replace("<", "&lt;").replace(">", "&gt;"), 13, color="#c0392b", anchor="end")
    ratio = real / max(dist)
    s += text(W/2, 296, f"dashed line: true value; bars: null distribution over 1000 permutations [-0.008, +0.009]; ratio ~ {ratio:.1f}x (p = 0.001)", 11, color="#c0392b")
    return s + svg_tail()

def fig6():
    author = json.load(open(os.path.join(OUT, "perm_depth5.json"), encoding="utf-8"))
    stdlib = json.load(open(os.path.join(OUT, "perm_stdlib.json"), encoding="utf-8"))
    ccorp = json.load(open(os.path.join(OUT, "perm_c.json"), encoding="utf-8"))
    W, H = 620, 380
    X0, X1, Y0, Y1 = -0.12, 0.32, -50, 45
    def X(x): return 70 + (x - X0) / (X1 - X0) * (W - 110)
    def Y(y): return 310 - (y - Y0) / (Y1 - Y0) * 260
    s = svg_head(W, H)
    s += text(W/2, 24, "Fig. 6  Sign consistency: per-file (&lt;D_asym&gt;, S(delta)) scatter", 15)
    s += line(X(X0), Y(0), X(X1), Y(0), "#333", 1)
    s += line(X(0), Y(Y0), X(0), Y(Y1), "#333", 1)
    for dset, color in [(author, "#c0392b"), (stdlib, "#1e6091"), (ccorp, "#1e8449")]:
        for f in dset["per_file"]:
            s += f'<circle cx="{X(f["mean"]):.1f}" cy="{Y(f["skew"]):.1f}" r="3.5" fill="{color}" opacity="0.75"/>\n'
    s += text(X(0.315), Y(0) + 18, "<D_asym> (per-file mean)".replace("<", "&lt;").replace(">", "&gt;"), 11, color="#333", anchor="end")
    s += text(X(0.02), Y(40), "S(delta)", 12)
    s += text(X(0.04), Y(0) + 20, "<D_asym> = 0".replace("<", "&lt;").replace(">", "&gt;"), 10, color="#333", anchor="end")
    s += text(160, 350, "red: Python author dataset (74); blue: Python stdlib (55); green: four C repos (168)", 12, color="#333")
    s += text(160, 368, "Python 129/129 satisfy &lt;D_asym&gt;&gt;0 and S(delta)&lt;0; C 146/168 (upper 22 points: noise floor / generated tables / zero-signal degeneracy, see Sec. 5.5)", 11, color="#c0392b")
    return s + svg_tail()

def main():
    for name, gen in [("fig1_sample_space", fig1), ("fig2_phase_ambiguity", fig2),
                      ("fig3_three_state", fig3), ("fig4_third_order", fig4),
                      ("fig5_perm_histogram", fig5), ("fig6_sign_scatter", fig6)]:
        path = os.path.join(OUT, name + ".svg")
        with open(path, "w", encoding="utf-8") as f:
            f.write(gen())
        print("written", path)

if __name__ == "__main__":
    main()
